#! /bin/sh

# $Id: kernel_modules,v 1.14 2009-07-16 00:23:49 brian Exp $
# Copyright (c)2007 Brian Manning <brian at portaboom dot com>

if ! [ -e $LACK_FUNCTIONS ]; then
    LACK_FUNCTIONS="/etc/scripts/lack_functions.sh"
fi # if ! [ -e $LACK_FUNCTIONS ]
source $LACK_FUNCTIONS
PATH=/sbin:/bin  # No remote fs at start
ACTION=$1
BINARY=/sbin/modprobe
[ -x "$BINARY" ] || exit 0
BASENAME="kernel-modules"
DESC="Loading kernel modules;"
BINARY_OPTS=""
MODULES_FILE="/etc/modules"

if [ ! -r $MODULES_FILE ]; then
    echo "ERROR: modules file $MODULES_FILE not found"
    cmd_status 1 
fi # if [ ! -r $MODULES_FILE ]

case "$ACTION" in
  vars)
    echo "${BASENAME}:"
    exit 0
  ;;
  start)
	colorize_nl $S_TIP "${BASENAME}: $DESC"
    for MODULE in $(cat $MODULES_FILE | grep -v "^#"); 
    do
	    colorize_nl $S_TIP "  - $MODULE"
    	$BINARY $BINARY_OPTS $MODULE >> $BOOT_LOG 2>&1
        cmd_status $?
    done
	colorize $S_TIP "${BASENAME}: All kernel modules in /etc/modules loaded;"
    colorize_nl $S_SUCCESS "${SUCCESS}"
	;;
  stop)
    # noop
    :
	;;
  restart|force-reload)
    # noop
    :
	;;
  *)
	echo "Usage: $BASENAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
