#! /bin/sh

# $Id: setvolume,v 1.2 2009-07-23 22:05:47 brian Exp $
# Copyright (c)2007 Brian Manning <elspicyjack at gmail dot com>

# picks up things like colorize()
source $ANT_FUNCTIONS

ACTION=$1
BINARY="/etc/scripts/setvolume.sh"
[ -x "$BINARY" ] || exit 1
BASENAME="setvolume"
DESC="ALSA Mixer Volume"
# don't mute sound by default
MUTE=0

# go into /proc/cmdline and see what options were used
# stream URL
file_parse "/proc/cmdline" "mute"
MUTE_CHECK=$PARSED
# some defaults
if [ "x$MUTE_CHECK" != "x" ]; then
    MUTE=1
fi # if [ "x$MUTE_CHECK" != "x" ]

# export these here so they get propagated to other scripts
export MUTE

# act on the argument passed in to this script
case "$ACTION" in
  vars)
    # echo out what commandline variables are parsed by this script
    echo "${BASENAME}:"
    exit 0
  ;;
  start)
	colorize $S_TIP "${BASENAME}: Starting ${DESC}"
    # mute all the channels on startup?
    if [ $MUTE -eq 0 ]; then
        # nope
    	$BINARY
        cmd_status $?
        colorize_nl $S_SUCCESS "$SUCCESS"
    else
        # yep
    	$BINARY --mute
        cmd_status $?
        colorize_nl $S_SUCCESS "$SUCCESS"
    fi # if [ "x$USE_WGET" != "x" ]
	;;
  stop)
	PATH=/bin:/sbin:/usr/bin:/usr/sbin
	colorize $S_TIP "${BASENAME}: Stopping ${DESC}"
    $BINARY --mute
    cmd_status $?
    colorize_nl $S_SUCCESS "$SUCCESS"
	;;
  restart|force-reload)
 	$0 stop
 	$0 start
	;;
  *)
	echo "Usage: $BASENAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
