#! /bin/sh

# $Id: mountall,v 1.4 2009-06-26 07:31:22 brian Exp $
# Copyright (c)2007 Brian Manning <elspicyjack at gmail dot com>

# picks up things like colorize()
source $ANT_FUNCTIONS

ACTION=$1
BINARY=/bin/mount
[ -x "$BINARY" ] || exit 1
BASENAME="mountall"
BINARY_OPTS="-r -c"
MP3_FILELIST="/tmp/foundlist.m3u"

## FUNC: mount_all_squashfs_packages
## ARG:  PKG_LIST, a list of squashfs packages to copy/mount
## DESC: Copies and mounts all squashfs (*.sfs) files found on to the ramdisk
## DESC: mounts the squashfs files, then creates symlink farms so that other
## DESC: binaries can use the mounted squashfs packages
function mount_all_squashfs_packages {
    local PKG_LIST=$1
    for SFS_FILE in $PKG_LIST; 
    do
        SFS_NAME=$(echo ${SFS_FILE} | sed 's/\.$sfs//')
        cp /mnt/cdrom/portaboom/pkgs/$SFS_FILE /tmp
        mkdir /tmp $SFS_NAME
        mount -t squashfs -o loop /tmp/$SFS_FILE /tmp/$SFS_NAME
    done # for SFS_FILE in $SFS_LIST
} # function mount_all_squashfs_packages

case "$ACTION" in
  vars)
    # echo out what commandline variables are parsed by this script
    echo "${BASENAME}:"
    exit 0
  ;;
  start)
    colorize_nl $S_TIP "$BASENAME: Checking for CD-ROM Devices..."
    CDROM_DEV=$(/sbin/udevadm info --query=name --name=cdrom)
    if [ $? -gt 0 ]; then
        colorize_nl "$BASENAME: udevadm can't find CD-ROM device;"
        colorize_nl "$BASENAME: skipping CD-ROM mounting"
    else
        colorize $S_TIP "$BASENAME: Mounting /dev/$CDROM_DEV "
        $BINARY -t iso9660 -o ro /dev/$CDROM_DEV /mnt/cdrom
        if [ $? -eq 0 ]; then
            colorize_nl $S_SUCCESS "$SUCCESS"
            # the mount worked, so run a find on the CD-ROM drive now
            SFS_LIST=$(find /mnt/cdrom/portaboom/pkgs -type f -iname "*.sfs")
            mount_all_squashfs_packages "${SFS_LIST}"
        fi
    fi # if [ $? -gt 0 ];

    colorize_nl $S_TIP "$BASENAME: Checking for Disk/Thumbdrive Devices..."
    for DISK in sda sdb sdc sdd sde sdf sdg hda hdb hdc hdd; do
        # skip testing the CD-ROM device
        if [ "x$DISK" = "x$CDROM_DEV" ]; then
            continue
        fi
        # skip devices that are already mounted for whatever reason
        if [ $(/bin/grep -c $DISK /proc/mounts) -gt 0 ]; then
            continue
        fi
        # we only care about the exit code; redirect output to /dev/null
        /sbin/udevadm info --query=name --name=${DISK} >/dev/null 2>&1
        if [ $? -eq 0 ]; then
            PARTITIONS=$(cat /proc/partitions | /bin/grep ${DISK} \
                | grep -v "${DISK}$" | /usr/bin/awk '{print $4}')
            for MNT_POINT in $(echo ${PARTITIONS}); do
                mkdir /mnt/$MNT_POINT
                colorize $S_TIP "$BASENAME: Mounting /dev/${MNT_POINT}"
                $BINARY -t auto -o ro /dev/$MNT_POINT \
                    /mnt/$MNT_POINT >> $BOOT_LOG 2>&1 
                if [ $? -eq 0 ]; then
                    colorize_nl $S_SUCCESS "$SUCCESS"
                    SFS_LIST=$(find /mnt/${MNT_POINT} \
                        -type f -iname "*.sfs")
                    mount_all_squashfs_packages "${SFS_LIST}"
                else
                    colorize_nl $S_FAILURE "$FAILED"
                fi
            done # for MNT_POINT in $(echo ${PARTITIONS});
        fi # if [ $? -eq 0 ];
    done # for DISK in hda hdb hdc hdd sda sdb sdc sdd sde sdf sdg
    ;; # start)
  stop)
    PATH=/bin:/sbin:/usr/bin:/usr/sbin
    #colorize $S_TIP "Unmounting all filesystems"
    echo "Unmounting all device-backed filesystems"
    for MOUNT in $(cat /proc/mounts | awk '{print $1}' | grep "^/dev");
    do
        echo " - $MOUNT"
        /bin/umount $MOUNT
    done
    ;; # stop)
  restart|force-reload)
     $0 stop
     $0 start
    ;;
  *)
    echo "Usage: $BASENAME {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac

:
