#! /bin/sh

# $Id: bbinit,v 1.2 2009-05-07 07:22:12 brian Exp $
# Copyright (c)2007 Brian Manning <elspicyjack at gmail dot com>

source $ANT_FUNCTIONS
ACTION=$1
BASENAME="bbinit"
DESC="Busybox init"

case "$ACTION" in
  vars)
    echo "${BASENAME}:"
    echo "cmdline - run; Runs Busybox init; use as the last init script to run"
    echo "comment - (run=bbinit)"
    exit 0
  ;;
  start)
    file_parse "/proc/cmdline" "run" # returns any parsed data as $PARSED
    RUN_PROG=$PARSED
    if [ "x$RUN_PROG" == "xbbinit" ]; then
    	colorize_nl $S_TIP "$BASENAME: $DESC"
	    colorize_nl $S_TIP "$BASENAME: Starting processes on virtual terminals"
        exec $BB init < dev/console > dev/console 2>&1
    else
        colorize_nl $S_TIP "$BASENAME: Skipping Busybox init"
    fi
	;; # start)
  stop)
    # noop
    :
	;; # stop)
  restart|force-reload)
    # noop
    :
	;;
  *)
	echo "Usage: $BASENAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
