#! /bin/sh

# $Id: klogd,v 1.13 2009-05-13 07:34:26 brian Exp $
# Copyright (c)2008 Brian Manning <elspicyjack at gmail dot com>
# PLEASE DO NOT E-MAIL THE AUTHOR ABOUT THIS SOFTWARE
# The proper venue for questions is the Antlinux mailing list at:
# http://groups.google.com/group/antlinux or <antlinux@googlegroups.com>

# this file will get touched if we're running in debug mode; this script will
# have already been run
if [ -e /var/run/debug ]; then exit 0; fi

source $ANT_FUNCTIONS
ACTION=$1
BINARY=/sbin/klogd
[ -x "$BINARY" ] || exit 1
DESC="kernel logger daemon"
BASENAME=$(/usr/bin/basename $BINARY)
# 0 = unstable, 1 = immediate, 2 = critical, 3 = error, 4 = warning
# 5 = normal, 6 = info, 7 = debug
KERNEL_LOG_LEVEL=4
BINARY_OPTS="-c ${KERNEL_LOG_LEVEL}"

case "$1" in
  vars)
    echo "${BASENAME}:"
    exit 0
  ;;
  start)
	colorize $S_TIP "${BASENAME}: Starting $DESC;"
	$BINARY $BINARY_OPTS
    cmd_status $?
    # get_pid sets $CHILD_PID
    get_pid $BINARY
    write_child_pid $BASENAME $CHILD_PID
    colorize "$S_SUCCESS" "$SUCCESS"
    echo -n " (PID=${CHILD_PID}, "
    echo "loglevel='${KERNEL_LOG_LEVEL}')"
	;;
  stop)
	PATH=/bin:/sbin:/usr/bin:/usr/sbin
    KLOGD_PID=$(cat /var/run/${BASENAME}.pid)
	colorize $S_TIP "${BASENAME}: Stopping $DESC "
    echo -n "(PID = ${KLOGD_PID});"
    /bin/kill -TERM $KLOGD_PID
    cmd_status $?
    colorize_nl "$S_SUCCESS" "$SUCCESS"
	;;
  restart|force-reload)
 	$0 stop
 	$0 start
	;;
  *)
	echo "Usage: $BASENAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
